name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Compile Java Application
      run: javac -d ./out ./src/main/java/ch/zhaw/deeplearningjava/celebclassification/ModelUploader.java

    - name: Run Java Application
      run: java -cp ./out ModelUploader "${{ secrets.AZURE_STORAGE_ACCESSKEY }}"

