name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: models # Verzeichnis, das die Artefakte enthält
          container_name: models # Name des Azure Blob Storage Containers
          connection_string: ${{ secrets.AZURE_STORAGE_ACCESSKEY }} # Verbindungszeichenfolge für Azure Blob Storage
          extra_args: '--pattern "celebclassifier-0001.params" --pattern "synset.txt"' # Muster, das auf die hochzuladenden Dateien zutrifft
          overwrite: 'true' # (optional) Überschreiben von vorhandenen Blobs
