name: Upload to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Upload files to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: 'models'
        container_name: 'model'
        connection_string: ${{ secrets.ACCESSKEY }}
        extra_args: '--pattern celebclassifier-0001.params --pattern synset.txt'
        
